title: Home
email: agneesh.barua@oist.jp
description: >- # this means to ignore newlines until "baseurl:"
Agneesh's webiste featuring latest news on research projects, publications, and more!
twitter_username: AgneeshBarua
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Jekyll configurations
#permalink: none
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Agneesh Barua"
  avatar : "/assets/images/profile.jpg"
  bio    : "Final year graduate student at the Okinawa Institute of Science and Technology Graudate University"
  links:
    - label: "Email"
      icon: "far fa-envelope"
      url: "agneesh.barua@oist.jp"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AgneeshBarua"
    - label: "Google Scholar"
      icon: "fas fa-user-graduate"
      url: "https://scholar.google.com/citations?user=1AcPd8kAAAAJ&hl=en"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true